export const columnData = [
  {
    field: 'name',
    headerName: 'Name',
    flex: 1,
  },

  {
    field: 'earnings',
    headerName: 'Earnings',
    flex: 1,
  },
  {
    field: 'trips',
    headerName: 'Trips',
    flex: 1,
  },
  {
    field: 'country',
    headerName: 'Country',
    type: 'string',
    flex: 1,
  },
  {
    field: 'status',
    headerName: 'status',
    flex: 1,
  },
  {
    field: 'takeaction',
    headerName: 'Take Action',
    flex: 1,
  },
]

export const rowData = [
  {
    id: 1,
    name: 'Ice T',
    country: 'country',
    earnings: '112,500',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 2,
    name: 'Peter M',
    country: 'country',
    earnings: '45256',
    trips: 80,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 3,
    name: 'Tonny J',
    country: 'country',
    earnings: '85,336',
    trips: 99,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 4,
    name: 'Aljem',
    country: 'country',
    earnings: '190,265',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 5,
    name: 'Topiada D',
    country: 'country',
    earnings: '100,000',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 6,
    name: 'Pinguta J',
    country: 'country',
    earnings: '854,788',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 7,
    name: 'Shaka Z',
    country: 'country',
    earnings: '100,000',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 8,
    name: 'Sam Z',
    country: 'country',
    earnings: '365,447',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
  {
    id: 9,
    name: 'Aljem',
    country: 'country',
    earnings: '778,562',
    trips: 20,
    status: 'status',
    takeaction: 'takeaction',
  },
]
