export const columnData = [
  {
    field: 'date',
    headerName: 'Date Added',
    flex: 1,
  },
  {
    field: 'name',
    headerName: 'Name',
    flex: 1,
  },
  {
    field: 'country',
    headerName: 'Country',
    flex: 1,
  },
  {
    field: 'department',
    headerName: 'Department',
    flex: 1,
  },
  {
    field: 'email',
    headerName: 'Email Address',
    type: 'number',
    flex: 1,
  },

  {
    field: 'phone',
    headerName: 'Phone',
    flex: 1,
  },
]

export const rowData = [
  {
    id: 0,
    date: '30 Oct,12:42',
    name: 'Israel Nantinda',
    country: 'South Africa',
    department: 'Top MGT',
    email: 'israel@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 1,
    date: '30 Oct,12:42',
    name: 'Joan Wangui',
    country: 'Zimbabwe',
    department: 'Top MGT',
    email: 'joan@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 2,
    date: '30 Oct,12:42',
    name: 'Samuel olwe',
    country: 'Uganda',
    department: 'Backend',
    email: 'samuel@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 3,
    date: '30 Oct,12:42',
    name: 'Joshua Odaga',
    country: 'Uganda',
    department: 'Backend',
    email: 'joshua@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 4,
    date: '30 Oct,12:42',
    name: 'Priscilla Kizza',
    country: 'Uganda',
    department: 'Design',
    email: 'priscilla.mary@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 5,
    date: '30 Oct,12:42',
    name: 'Joshua komakech',
    country: 'NIgeria',
    department: 'Front End',
    email: 'komakech@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 6,
    date: '30 Oct,12:42',
    name: 'John Komakech',
    country: 'Nigeria',
    department: 'Front End',
    email: 'komakech@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 7,
    date: '30 Oct,12:42',
    name: 'Koichi Someone',
    country: 'China',
    department: 'Front End',
    email: 'koichi@getbukk.com',
    phone: '+1080055432',
  },
  {
    id: 8,
    date: '30 Oct,12:42',
    name: 'Jobulon Alyaa',
    country: 'Uganda',
    department: 'Design',
    email: 'emmanuel.jabulon@getbukk.com',
    phone: '+1080055432',
  },
]
